package:
  name: "pyconll"
  version: "3.0.3"

source:
  path: ./

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pyconll
    - pyconll.tree
    - pyconll.unit
    - util

about:
  home: "https://github.com/pyconll/pyconll"
  license: "MIT"
  license_family: "MIT"
  license_file: "{{ environ['RECIPE_DIR'] }}/LICENSE"
  summary: "Read and manipulate CoNLL files"
  description: "Read and manipulate CoNLL files"
  doc_url: "https://pyconll.readthedocs.io/en/stable/"
  dev_url: "https://github.com/pyconll/pyconll"

extra:
  recipe-maintainers:
    - matgrioni
